function structOut = getMOD_VIPAstruct(self)
           structOut = struct();
           structOut.spectrumY = self.spectrumY;
           structOut.spectrumX = self.spectrumX;
           structOut.xAxis = self.xAxis;
           structOut.yAxis = self.yAxis;
           structOut.refSpectrumY = self.refSpectrumY;
           structOut.calibrationImages_reference = self.calibrationImages_reference;
           structOut.calibrationImages_referenceBackground = self.calibrationImages_referenceBackground;
           structOut.calibrationImages_calibrationGas = self.calibrationImages_calibrationGas;
           structOut.calibrationImages_calibrationGasBackground = self.calibrationImages_calibrationGasBackground;
           structOut.fringeImageSize = self.fringeImageSize;
           structOut.spectrumIdcs = self.spectrumIdcs;
           structOut.fringeX = self.fringeX;
           structOut.fringeY = self.fringeY;
           structOut.fringeXcrop = self.fringeXcrop;
           structOut.fringeYcrop = self.fringeYcrop;
           structOut.fringeHeight = self.fringeHeight;
           structOut.numFringes = self.numFringes;
           structOut.calibrationGas = self.calibrationGas;
           structOut.calibrationGasPartialPressure = self.calibrationGasPartialPressure;
           structOut.calibrationGasPathLength = self.calibrationGasPathLength;
           structOut.fringeThreshold = self.fringeThreshold;
           structOut.imgsPerBackground = self.imgsPerBackground;
end